### ISSUE TITLE
鼠标指上物品时出现的框框内没有汉化

### ISSUE THREAD

**Issue by detiam** [Enaium-FabricMC/OmniTranslation#1]
![无标题](https://user-images.githubusercontent.com/44510779/84534152-0141cb00-ad1c-11ea-98ca-189b1f182d4b.png)
如图所示，但是框缩小到了四个字宽的长度

**Comment by Enaium** [comment]
是1.15.2吧

**Comment by Enaium** [comment]
这个mod可以添加语言文件不需要使用此MOD

**Comment by Enaium** [comment]
我看了一下 "Press B to open the Upgrade inventory" 这个字符串不在语言文件里

**Comment by Enaium** [comment]
等我修

**Comment by Enaium** [comment]
![txjW4g.png](https://s1.ax1x.com/2020/06/14/txjW4g.png)

已经修复
