### ISSUE TITLE
在“搜索物品”分类下物品详情信息上的翻译不生效

### ISSUE THREAD

**Issue by detiam** [Enaium-FabricMC/OmniTranslation#2]
![image](https://user-images.githubusercontent.com/44510779/84588850-415c9700-ae5d-11ea-8239-2fed31dc4d23.png)
RT

**Comment by Enaium** [comment]
什么意思

**Comment by Enaium** [comment]
等我修

**Comment by Enaium** [comment]
![NVckOP.png](https://s1.ax1x.com/2020/06/17/NVckOP.png)
好了
